# Generated by Django 4.0.5 on 2022-06-22 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='상품명')),
                ('image', models.FileField(upload_to='productimg', verbose_name='썸네일')),
                ('dec', models.TextField(verbose_name='상품설명')),
                ('registered_date', models.DateField(auto_now_add=True, verbose_name='등록일')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='등록일')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='노출 시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='노출 종료일')),
                ('status', models.CharField(choices=[('판매중', '판매중'), ('판매종료', '판매종료')], max_length=30, verbose_name='활성화 여부')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(verbose_name='리뷰')),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='작성일')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='작성자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
