# Generated by Django 4.0.5 on 2022-06-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated_date',
            field=models.DateField(auto_now=True, verbose_name='등록일'),
        ),
    ]
