# Generated by Django 4.0.5 on 2022-06-20 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='strat_date',
            new_name='start_date',
        ),
    ]
