# Generated by Django 4.0.5 on 2022-06-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_strat_date_article_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='노출 종료일'),
        ),
        migrations.AlterField(
            model_name='article',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='노출 시작일'),
        ),
    ]
