# Generated by Django 4.0.5 on 2022-06-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hobby',
            field=models.ManyToManyField(related_name='hobby', to='user.hobby', verbose_name='취미'),
        ),
    ]
